vim.api.nvim_set_keymap('n', '<F2>', ':NvimTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-s>', ':w<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<F3>', ':Telescope find_files<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<S-F3>', ':Telescope<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<F4>', ':LazyGit<CR>', {noremap = true})
