return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    config = {
        ensure_installed = {
            "bash",
            "c",
            "cmake",
            "css",
            "csv",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "hyprlang",
            "json",
            "json5",
            "jsonc",
            "lua",
            "luadoc",
            "luap",
            "luau",
            "make",
            "markdown",
            "markdown_inline",
            "passwd",
            "powershell",
            "python",
            "query",
            "regex",
            "ssh_config",
            "toml",
            "vim",
            "vimdoc",
            "yaml",
        },
        sync_install = false,
        auto_install = false,
        highlight = {
            enable = true,
        },
    },
}
