vim.api.nvim_set_hl(0, "Normal", {fg="#FF0055", bg="NONE"})
vim.api.nvim_set_hl(0, "Visual", {reverse=true})
vim.api.nvim_set_hl(0, "ColorColumn", {fg="#ff0055"})
vim.api.nvim_set_hl(0, "LineNr", {fg="#ff0055"})
vim.api.nvim_set_hl(0, "SignColumn", {fg="#00FFC8"})
vim.api.nvim_set_hl(0, "VertSplit", {fg="#FF0055", bg="#101116"})
vim.api.nvim_set_hl(0, "IncSearch", {bg="#283593"})
vim.api.nvim_set_hl(0, "Search", {bg="#283593"})
vim.api.nvim_set_hl(0, "Substitute", {bg="#283593"})
vim.api.nvim_set_hl(0, "MatchParen", {fg="#FF0055", bg="#55ff00"})
vim.api.nvim_set_hl(0, "NonText", {fg="#2B3E5A"})
vim.api.nvim_set_hl(0, "WildMenu", {fg="#00FFC8", bold=true})
vim.api.nvim_set_hl(0, "Title", {fg="#C592FF"})
vim.api.nvim_set_hl(0, "Comment", {fg="#6766b3"})
vim.api.nvim_set_hl(0, "String", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Number", {fg="#fffc58"})
vim.api.nvim_set_hl(0, "Float", {fg="#fffc58"})
vim.api.nvim_set_hl(0, "Boolean", {fg="#fffc58"})
vim.api.nvim_set_hl(0, "Character", {fg="#fffc58"})
vim.api.nvim_set_hl(0, "Conditional", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Repeat", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Label", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Exception", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Operator", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Keyword", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "StorageClass", {fg="#d57bff"})
vim.api.nvim_set_hl(0, "Statement", {fg="#76C1FF"})
vim.api.nvim_set_hl(0, "Function", {fg="#d57bff"})
vim.api.nvim_set_hl(0, "Identifier", {fg="#EEFFFF"})
vim.api.nvim_set_hl(0, "PreProc", {fg="#00FF9C"})
vim.api.nvim_set_hl(0, "Type", {fg="#00FF9C"})
vim.api.nvim_set_hl(0, "Structure", {fg="#00FF9C"})
vim.api.nvim_set_hl(0, "Typedef", {fg="#00FF9C"})
vim.api.nvim_set_hl(0, "Todo", {fg="#00FF9C", bg="#372963", italic=true})
vim.api.nvim_set_hl(0, "Error", {fg="#ff3270", undercurl=true})
vim.api.nvim_set_hl(0, "WarningMsg", {fg="#009550"})
vim.api.nvim_set_hl(0, "Special", {fg="#00FF9C", italic=true})
vim.api.nvim_set_hl(0, "Tag", {fg="#00FF9C", undercurl=true})
vim.api.nvim_set_hl(0, "Pmenu", {fg="#ff0055", bg="#140007"})
vim.api.nvim_set_hl(0, "PmenuSel", {fg="#140007", bg="#ff0055"})
vim.api.nvim_set_hl(0, "PmenuSbar", {bg="#ff0055"})
vim.api.nvim_set_hl(0, "PmenuThumb", {})
vim.api.nvim_set_hl(0, "StatusLine", {fg="#ff0055", bg="#1d000a", bold=true})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg="#ff0055", bg="#000000"})
vim.api.nvim_set_hl(0, "TabLine", {fg="#FF4081"})
vim.api.nvim_set_hl(0, "TabLineSel", {fg="#FF4081", bold=true})
vim.api.nvim_set_hl(0, "Folded", {fg="#00FFC8", italic=true})
vim.api.nvim_set_hl(0, "FoldColumn", {fg="#00FFC8"})

-- this theme is actually a custom version of https://github.com/thedenisnikulin/vim-cyberpunk
